In [1]:
import numpy as np
import gym
import time
from lake_envs import *
import value_iteration
import utility
import tabQ_learning
%load_ext autoreload
%autoreload 2

# Q4

6*10^5 seems to be a sufficient amount of itterations to be 0.05-optimal

In [110]:
env = gym.make('Deterministic-4x4-FrozenLake-v0')
Q = tabQ_learning.Qlearning(env, num_observations = 6*10**5)
value_iteration.isQvalueErrorEpsilonClose(env, Q, gamma=0.95, epsilon=0.05)
#utility.compute_statistics(env, Q)

function took 13827.309 ms
Great!! The value of your provided Q is 0.7660485714488815, and this is 0.05 close to the optimal value of 0.7737809374999999


True

# Q5
A less than linear decay seems to be beneficial. This also seems reasonable from the \sum alpha = inf but also \sum alpha^2 < inf

In [252]:
env = gym.make('Deterministic-4x4-FrozenLake-v0')
lr = lambda x: utility.polynomial_learning_rate(x, 0.1)
Q = tabQ_learning.Qlearning(env,gamma=0.95, num_observations = 8*10**2, learning_rate=lr )
print(Q)
value_iteration.isQvalueErrorEpsilonClose(env, Q, gamma=0.95, epsilon=0.05)

Function took 23.342 ms
[[ 0.73413533  0.77359878  0.77365397  0.73442399]
 [ 0.73491397  0.          0.8144909   0.77307639]
 [ 0.77373081  0.85737385  0.77368306  0.81448876]
 [ 0.81450151  0.          0.77122431  0.7737277 ]
 [ 0.7735587   0.81449659  0.          0.73483439]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.90249951  0.          0.81440668]
 [ 0.          0.          0.          0.        ]
 [ 0.81448799  0.          0.85737497  0.77343215]
 [ 0.81367083  0.9025      0.90249999  0.        ]
 [ 0.857375    0.95        0.          0.85737451]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.9025      0.95        0.85737499]
 [ 0.90249987  0.95        1.          0.90249999]
 [ 0.          0.          0.          0.        ]]
Great!! The value of your provided Q is 0.7736539715109277, and this is 0.05 close to the optimal value of 0.7737809374999999


True

In [259]:
env = gym.make('Deterministic-4x4-FrozenLake-v0')
Q = tabQ_learning.speedy_Qlearning(env,gamma=0.95, num_observations = 6*10**4 )
value_iteration.isQvalueErrorEpsilonClose(env, Q, gamma=0.95, epsilon=0.05)


0.0
1.0
1 upgraded
1.0
2.5
2 upgraded
2.5
1.74166666667
3 upgraded
1.74166666667
1.27854166667
4 upgraded
1.27854166667
0.98598125
5 upgraded
0.98598125
0.787356041667
6 upgraded
0.787356041667
0.644817447917
7 upgraded
0.644817447917
0.88318452381
8 upgraded
0.88318452381
0.802112268519
9 upgraded
0.802112268519
1.35509259259
10 upgraded
1.35509259259
1.22168560606
11 upgraded
1.22168560606
1.1004916351
12 upgraded
1.1004916351
3.25133547009
13 upgraded
3.25133547009
2.90850503663
14 upgraded
2.90850503663
2.60955009921
15 upgraded
2.60955009921
2.34780831163
16 upgraded
2.34780831163
2.11774120424
17 upgraded
2.11774120424
1.9147495884
18 upgraded
1.9147495884
1.73500672479
19 upgraded
1.73500672479
2.95598684211
20 upgraded
2.95598684211
2.70586011905
21 upgraded
2.70586011905
2.47948200758
22 upgraded
2.47948200758
2.27437357337
23 upgraded
2.27437357337
2.0883158206
24 upgraded
2.0883158206
1.9193313746
25 upgraded
1.9193313746
1.76566244852
26 upgraded
1.76566244852
0.32370958401

False

In [58]:
Q

array([[ 0.02816597,  0.02880586,  0.03026623,  0.02200452],
       [ 0.01503123,  0.0305485 ,  0.03131401,  0.03843271],
       [ 0.08838523,  0.07946998,  0.0935716 ,  0.03959607],
       [ 0.03044721,  0.02997601,  0.01646211,  0.0389029 ],
       [ 0.07241955,  0.06714368,  0.05513556,  0.02058766],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.19142259,  0.18225521,  0.15328032,  0.02657085],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.06803552,  0.16429744,  0.10251374,  0.20342147],
       [ 0.23375191,  0.40932891,  0.33653584,  0.20424869],
       [ 0.46401755,  0.44361195,  0.33829917,  0.15877389],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.33234811,  0.46930152,  0.57143516,  0.35767393],
       [ 0.60604058,  0.80757963,  0.77077813,  0.71420912],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])