In [2]:
import numpy as np
import gym
import time
from lake_envs import *
import value_iteration
import utility
import tabQ_learning
%load_ext autoreload
%autoreload 2

# Q4

6*10^5 seems to be a sufficient amount of itterations to be 0.05-optimal

In [32]:
env = gym.make('Deterministic-4x4-FrozenLake-v0')
Q = tabQ_learning.Qlearning(env, num_observations = 6*10**5)
value_iteration.isQvalueErrorEpsilonClose(env, Q, gamma=0.95, epsilon=0.05)
#utility.compute_statistics(env, Q)

Function took 15952.613 ms
Great!! The value of your provided Q is 0.7703915957613292, and this is 0.05 close to the optimal value of 0.7737809374999999


True

# Q5
A less than linear decay seems to be beneficial. This also seems reasonable from the \sum alpha = inf but also \sum alpha^2 < inf

In [47]:
env = gym.make('Deterministic-4x4-FrozenLake-v0')
lr = lambda x: utility.polynomial_learning_rate(x, 0.000)
Q = tabQ_learning.Qlearning(env,gamma=0.95, num_observations = 4*10**3, learning_rate=lr )
print(Q)
value_iteration.isQvalueErrorEpsilonClose(env, Q, gamma=0.95, epsilon=0.05)

Function took 125.240 ms
[[ 0.73509189  0.77378094  0.77378094  0.73509189]
 [ 0.73509189  0.          0.81450625  0.77378094]
 [ 0.77378094  0.857375    0.77378094  0.81450625]
 [ 0.81450625  0.          0.77378094  0.77378094]
 [ 0.77378094  0.81450625  0.          0.73509189]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.9025      0.          0.81450625]
 [ 0.          0.          0.          0.        ]
 [ 0.81450625  0.          0.857375    0.77378094]
 [ 0.81450625  0.9025      0.9025      0.        ]
 [ 0.857375    0.95        0.          0.857375  ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.9025      0.95        0.857375  ]
 [ 0.9025      0.95        1.          0.9025    ]
 [ 0.          0.          0.          0.        ]]
Great!! The value of your provided Q is 0.7737809374999999, and this is 0.05 close to the optimal value of 0.7737809374999999


True

# Q7

In [30]:
env = gym.make('Deterministic-4x4-FrozenLake-v0')
Q = tabQ_learning.speedy_Qlearning(env,gamma=0.95, num_observations = 6*10**4 )
value_iteration.isQvalueErrorEpsilonClose(env, Q, gamma=0.95, epsilon=0.05)


Function took 4154.796 ms
Great!! The value of your provided Q is 0.754141827411168, and this is 0.05 close to the optimal value of 0.7737809374999999


True

# Q8 
It seems that with the default learning rate speedy Q-learning beats the standard version with at least an order of magnitude but still takes long in terms of execution time. This would not be a factor if the simulation environment took more time relative to the algorithm execution. 